#cloud-config
coreos:
  fleet:
    public-ip: "$private_ipv4"
    metadata: "cluster={{cluster}}"
    etcd_servers: "http://{{etcd-cluster-dns}}.japanwest.cloudapp.azure.com:2379"
  units:
    - name: fleet.service
      command: start
    - name: fleet.socket
      drop-ins:
        - name: "30-ListenStream.conf"
          content: |
            [Socket]
            ListenStream=$private_ipv4:49153

